export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';
export const DISMISS_ERROR = 'DISMISS_ERROR';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const COUNTRIES = [
  'belgium',
  'netherlands',
  'france',
  'germany',
  'luxemburg',
  'italy',
  'unitedKingdom',
];

export const REQUEST_STATUSSES = {
  FAILURE: 'FAILURE',
  REQUEST: 'REQUEST',
  SUCCESS: 'SUCCESS',
};